server:
  port: 8088

spring:
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./h2-db/gildedrose
    username: gildedrose
    password: gildedrose
    driverClassName: org.h2.Driver

  data:
    rest:
      base-path: /api/gilded-rose

surgeprice:
  config:
    surgeByPercent: .10
    surgeThreshold: 3
    surgeInterval: 10

